### PR TITLE
feat: add stale-while-revalidate cache adaptor

### PR DESCRIPTION
**Pull request by ms-fadaei**
I added an adaptor as my need to the project.

This adaptor is like the cache adaptor but with an additional stale-while-revalidate strategy. So cached response can be staled while validated.

This is my first pull request to contribute🙏

### CODE REVIEW

**Comment by ms-fadaei** [comment]
@kuitos, please can you review this pull request?

**Comment by ms-fadaei** [comment]
> Sorry for the delay reply, in vacation lately.
> 
> I have notice that the feature is built on cache adapter? Could we add the options to existed cacheAdapterEnhancer, rather than copy the code and build another one?

I hope you had enjoyed your vacation.

Yes. This adaptor is based on the cache adaptor. But they have key differences in cache implementation. This adaptor saves the next validation date besides the response promise so the cache has two keys: `responsePromise` and `revalidateDate`.

We can merge themes but for someone who doesn't want to use revalidate feature, there is a small runtime overhead (I think!).

**Comment by ms-fadaei** [comment]
@kuitos 
Can we make decisions on this pull request? I want to create a Nuxt module base on this feature to use inside my projects

**Comment by kuitos** [comment]
Looked into the pr you made, seems like the swr cache feature could be implement by [a custom cache](https://github.com/kuitos/axios-extensions/#more-advanced), rather than create a new cache enhancer?

**Comment by ms-fadaei** [comment]
I don't think so.

In my opinion, there are aspects that can be this implementation hard or even impossible:
1. As you know, the user can't find out what is the request index outside the modules. `const index = buildSortedURL(url, params, paramsSerializer);`
2. The user must engage with how to implement of SWR strategy (so why we develop such an extension?)
3. With the custom cache implementation, the user may engage with multiple if with Axios request and that is not what we want in our projects.
4. SWR is a standard strategy so we may want a standard way to use it.

I think this is ok to add an advanced SWR cache for users who just want to use it without any knowledge of how it worked!

Sorry for my bad English!

**Comment by ms-fadaei** [comment]
Dear @kuitos, can we speed up reviewing this pull request a little? As I mentioned, I plan to create a Nuxt module based on it.  Thank you so much.

**Comment by kuitos** [comment]
Thanks for your clarification, it does make sense.
As [stale-while-revalidate cache](https://datatracker.ietf.org/doc/html/rfc5861) is an extension of cache control, I prefer add this feature to cacheAdapterEnhancer, rather than make another one, could you please do some efforts to integrate them? The runtime overhead is doesn't matter, you do not have to struggle with this, otherwise we should separate every feature into an individual module, as we can not figure out whether all the features are be used or not.

Quite a busy these days, feels free to remind me while I not replied😆

**Comment by kuitos** [comment]
Thanks for your clarification, it does make sense.
As [stale-while-revalidate cache](https://datatracker.ietf.org/doc/html/rfc5861) is an extension of cache control, I prefer add this feature to cacheAdapterEnhancer, rather than make another one, could you please do some efforts to integrate them? The runtime overhead is doesn't matter, you do not have to struggle with this, otherwise we should separate every feature into an individual module, as we can not figure out whether all the features are be used or not.

Quite a busy these days, feels free to remind me while I not replied😆

**Comment by ms-fadaei** [comment]
Thanks for your reply. I'm sorry for interrupting your work but I need this feature as soon as possible 😃

The whole idea can be fit inside the `cacheAdapterEnhancer` but we must sure that the existing projects based on it won't break (I believe the existing test should help us)

If you want to merge this feature with `cacheAdapterEnhancer`, Can we close this PR, and then I start merging them in another one?

**Comment by kuitos** [comment]
Alright I will close this pr now.

BTW, you could close your pr and open another one by yourself, it's free😆.

**Pull request closed without merging**
